project:
  type: book
  output-dir: _book

book:
  title: "Make the Call"
  subtitle: "Knowing what you know, learning what you can, and acting under uncertainty in entrepreneurship"
  reader-mode: true

#  author: "Nile Hatch"
#  date: "9/4/2025"

  site-url: https://mc.nilehatch.com/
  repo-url: https://github.com/nilehatch/make_call/

  page-footer:
    left: |
      _Make the Call_ is written by Nile Hatch.
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.

  sidebar:
    style: "docked"
    collapse-level: 1

  chapters:
    - index.qmd
    - intro.qmd
    - part: part1-knowing-deciding.qmd
      chapters:
        - ch02-uncertainty.qmd
        - ch03-knowledge.qmd
        - ch04-epistemology.qmd
        - ch05-judgment.qmd
        - ch06-update-revise.qmd
        - wrap1-knowing-revising.qmd

    - part: part2-asking-right-questions.qmd
      chapters:
        - ch08-urgent-unknowns.qmd
        - ch09-hypotheses.qmd
        - ch10-exploration.qmd
        - wrap2-asking-right-questions.qmd

    - part: part3-gather-evidence.qmd
      chapters:
        - ch12-gathering-evidence.qmd
        - ch13-public-data.qmd        
        - ch14-private-data.qmd
        - ch15-customer-evidence.qmd
        - ch16-competitor-market-signals.qmd
        - ch17-ai-experts.qmd        
        - ch18-internal-data.qmd
        - ch19-modeling.qmd        

    - part: part4-judging-deciding-acting.qmd
      chapters:
        - ch21-updating.qmd
        - ch22-evaluating.qmd
        - ch23-decision-rules.qmd
        - ch24-judgment.qmd
        - ch25-presenting.qmd

    - part: part5-becoming.qmd
      chapters:
        - ch27-conviction.qmd
        - ch28-lifelong-learning.qmd
        - ch29-leadership.qmd
        
    - part: part6-evidence-toolkit.qmd
      chapters:
        - tk1-public-data.qmd
        - tk2-private-data.qmd
        - tk3-customer-data.qmd
        - tk4-customer-market-signals.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
      - base.css
      - custom-mtc.css
    number-sections: true
    number-depth: 1
    fig-cap-location: margin
    tbl-cap-location: margin

editor: source

execute:
  echo: false