project:
  type: book
  output-dir: _book

book:
  title: "Make the Call"
  subtitle: "Knowing what you know, learning what you can, and acting under uncertainty in entrepreneurship"
  reader-mode: true

#  author: "Nile Hatch"
#  date: "9/4/2025"

  site-url: https://mc.nilehatch.com/
  repo-url: https://github.com/nilehatch/make_call/

  page-footer:
    left: |
      _Make the Call_ is written by Nile Hatch.
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.

  sidebar:
    style: "docked"
    collapse-level: 1

  chapters:
    - index.qmd
    - intro.qmd
    - part: part1-knowing-deciding.qmd
      chapters:
        - ch01-uncertainty.qmd
        - ch02-knowledge.qmd
        - ch03-epistemology.qmd
        - ch04-judgment.qmd
        - ch05-bayesian.qmd

    - part: part2-asking-right-questions.qmd
      chapters:
        - ch06-urgent-unknowns.qmd
        - ch07-hypotheses.qmd
        - ch08-exploration.qmd

    - part: part3-gather-evidence.qmd
      chapters:
        - ch09-public-data.qmd
        - ch10-private-data.qmd
        - ch11-customer-evidence.qmd
        - ch12-ai-experts.qmd
        - ch13-modeling.qmd
        - ch14-accounting.qmd

    - part: part4-judging-deciding-acting.qmd
      chapters:
        - ch15-updating.qmd
        - ch16-evaluating.qmd
        - ch17-decision-rules.qmd
        - ch18-judgment.qmd
        - ch19-presenting.qmd

    - part: part5-becoming.qmd
      chapters:
        - ch20-faith.qmd
        - ch21-lifelong-learning.qmd
        - ch22-leadership.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
      - base.css
      - custom-mtc.css
    number-sections: true
    number-depth: 1
    fig-cap-location: margin
    tbl-cap-location: margin

editor: source

execute:
  echo: false